runtime: nodejs
env: flex
runtime_config:
  operating_system: 'ubuntu22'
  runtime_version: '18'
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
